/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<
      'home',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'components.autocomplete': RouteRecordInfo<
      'components.autocomplete',
      '/components/autocomplete',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'components.filters': RouteRecordInfo<
      'components.filters',
      '/components/filters',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'components.image': RouteRecordInfo<
      'components.image',
      '/components/image',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'components.phone-field': RouteRecordInfo<
      'components.phone-field',
      '/components/phone-field',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'components.time-field': RouteRecordInfo<
      'components.time-field',
      '/components/time-field',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'home'
      views:
        | never
    }
    'src/pages/components/autocomplete.vue': {
      routes:
        | 'components.autocomplete'
      views:
        | never
    }
    'src/pages/components/filters.vue': {
      routes:
        | 'components.filters'
      views:
        | never
    }
    'src/pages/components/image.vue': {
      routes:
        | 'components.image'
      views:
        | never
    }
    'src/pages/components/phone-field.vue': {
      routes:
        | 'components.phone-field'
      views:
        | never
    }
    'src/pages/components/time-field.vue': {
      routes:
        | 'components.time-field'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
